
server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE