server:
  port: 8083

spring:
  application:
    name: ORDER-SERVICE

  datasource:
    url: jdbc:mysql://103.218.122.180:3306/ms-shopping-cart
    username: trandat
    password: 123456789

  jpa:
    hibernate:
    #  ddl-auto: none
      ddl-auto: update
    #  ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect